#!/usr/bin/env bash
# ============================================================================
# stage_test.sh — tests validation stage
# Generated by Guardian Framework
# ============================================================================
set -euo pipefail

echo "============================================"
echo "  Stage: test"
echo "============================================"

echo "Running: bun test"
if bun test; then
    echo "✅ Stage test passed"
    exit 0
else
    echo "❌ Stage test failed"
    exit 1
fi
