#!/usr/bin/env bash
# ============================================================================
# stage_build.sh — ci validation stage
# Generated by Guardian Framework
# ============================================================================
set -euo pipefail

echo "============================================"
echo "  Stage: build"
echo "============================================"

echo "Running: bun run build"
if bun run build; then
    echo "✅ Stage build passed"
    exit 0
else
    echo "❌ Stage build failed"
    exit 1
fi
